dist: bionic
language: python
sudo: false
addons:
  postgresql: "9.6"

services:
  - mongodb

env:
  - BLITZDB_SQLALCHEMY_URL: "postgres://postgres@localhost/blitzdb_test"
  - BLITZDB_SQLALCHEMY_URL: "sqlite:///:memory:"

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install poetry

# command to run tests
before_script:
  - psql -c 'create database blitzdb_test;' -U postgres
  - sleep 3

script:
  - echo $BLITZDB_SQLALCHEMY_URL
  - tox
