dist: xenial
language: python
sudo: false
addons:
  postgresql: "9.6"

services:
  - mongodb

before_script:
  - psql -c 'create database blitzdb_test;' -U postgres
  - sleep 3

env:
  - BLITZDB_SQLALCHEMY_URL: "postgres://postgres@localhost/blitzdb_test"
  - BLITZDB_SQLALCHEMY_URL: "sqlite:///:memory:"

python:
  - "2.7"
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - pip install .
  - pip install -r requirements-travis.txt
  - echo $BLITZDB_SQLALCHEMY_URL

# command to run tests
script:
  - pytest
